/* ===========================================================
   Shared project data — consumed by index cards & project.html
   Add or edit entries here; the detail page renders from this.
   =========================================================== */
window.PROJECTS = {
  'ai-visual': {
    title: 'AI Visual Testing Framework',
    badge: 'AI · Visual',
    period: '2026',
    tagline: 'A visual regression framework combining Playwright, Applitools Visual AI and Claude — it catches UI regressions and automatically explains what went wrong.',
    stack: ['TypeScript', 'Node.js 18+', 'Playwright', 'Applitools Visual AI', 'Allure', 'Claude Vision API', 'Headless Chromium'],
    highlights: [
      "Visual checkpoint suite using Applitools' AI to detect only meaningful UI diffs — ignoring rendering noise, surfacing real regressions.",
      'Automatic failure enrichment: each failed test gets baseline/actual/diff images plus an inline Claude vision verdict (regression, functional bug, or flake).',
      'Dual reporting: an interactive Allure dashboard with per-test diff images, plus a shareable PDF generated via headless Chromium.',
      'Custom Applitools fixture handles session lifecycle, diff fetching and Allure enrichment automatically — no per-test wiring.',
      'Claude Code integration via /run-visual-tests and /analyze-visual-failures skills, plus a triage subagent that classifies failures and recommends actions.',
    ],
    github: null,
  },
  'api-rest-assured': {
    title: 'API Test Automation Framework',
    badge: 'API',
    period: '2026',
    tagline: 'An AI-augmented API automation framework built from the ground up, targeting a real auth + CRUD REST API with 18 end-to-end tests running out of the box.',
    stack: ['Java 17', 'Maven', 'Rest Assured 5.5', 'Hamcrest', 'JSON Schema Validator', 'TestNG 7.10', 'Extent Reports', 'GitHub Actions'],
    highlights: [
      'Full API coverage: health checks, auth flows, CRUD, negative/security paths, contract tests and data-driven scenarios.',
      'Self-healing suite: transient-only retry (5xx/timeouts), automatic token refresh on 401/403, and CRUD precondition recovery — real defects still fail fast.',
      'Dual reporting: interactive Extent HTML dashboard and a branded PDF with a summary donut chart and per-test request/response evidence.',
      'Layered architecture cleanly separating config, models, API clients and tests.',
      'CI via GitHub Actions runs the suite on push/PR and uploads reports as artifacts.',
    ],
    github: 'https://github.com/Kavindu-Dilshan-Dev',
  },
  'cross-browser': {
    title: 'Cross-Browser Testing + AI',
    badge: 'Cross-Browser · AI',
    period: '2026',
    tagline: 'An AI-powered framework that runs UI tests simultaneously across Chrome, Edge, Firefox and Safari (WebKit), then produces a PDF report analysing cross-browser consistency.',
    stack: ['TypeScript', 'Node.js 18+', 'Playwright (Chromium/Gecko/WebKit)', 'Claude Opus', 'GitHub Actions'],
    highlights: [
      'Parallel execution across all four browser engines from a single test script — no duplication, no browser-specific code.',
      'AI test generation: converts plain-English user flows into ready-to-run Playwright specs.',
      'Autonomous test-author agent explores the live DOM, writes a spec, self-verifies across all four browsers, and saves only when all pass.',
      'Self-healing agent detects broken locators, inspects the live page, applies a minimal fix and re-verifies before overwriting.',
      'Orchestrator agent coordinates generation, cross-browser runs, self-healing and reporting from a single goal prompt.',
      'PDF report with an executive summary, per-browser results table, consistency matrix, Claude findings and inlined screenshots.',
    ],
    github: null,
  },
  'jmeter-perf': {
    title: 'API Performance Testing (JMeter)',
    badge: 'Performance',
    period: '2026',
    tagline: 'An AI-assisted performance testing framework for REST APIs, combining JMeter as the load engine with Claude Code for test authoring and result analysis.',
    stack: ['Apache JMeter 5.6.3', 'PowerShell', 'Node.js', 'GitHub Actions', 'Claude Code'],
    highlights: [
      'A single parameterized JMeter plan supports four test types: load, stress, soak and baseline.',
      'AI-integrated workflow via the /perf-test skill — confirms the target, selects the right profile, reads the JTL, and reports a PASS/FAIL verdict with root-cause analysis.',
      'Fully portable: JMeter is bundled in the repo, with no external dependencies required to run.',
    ],
    github: null,
  },
  'appium-mobile': {
    title: 'Mobile QA Framework (Appium)',
    badge: 'Mobile · Security',
    period: '2026',
    tagline: 'A production-grade mobile test automation framework for a synthetic FinTech wallet app, engineered with security and compliance at its core.',
    stack: ['Java 17', 'Maven', 'JUnit Platform', 'Appium 2.x', 'Cucumber (BDD)', 'Extent Reports'],
    highlights: [
      'End-to-end BDD automation covering login, fund transfers, OTP flows and biometric authentication across Android and iOS.',
      'Fintech-hardened security layer: all PAN, CVV, OTP, IBAN and JWT tokens masked via a custom MaskingUtil before reaching any log or report.',
      'OTP and biometric flows fully simulated — no real SMS or sensors; secrets via environment variables only; zero hardcoded credentials.',
      'Luhn-valid synthetic card and account data via LuhnGenerator and TestDataFactory.',
      'Compliance traceability through Cucumber tags (@PCI-DSS-*, @REQ-*); cloud and local device support (BrowserStack / AVD / iOS Simulator).',
    ],
    github: null,
  },
  'cypress': {
    title: 'Cypress Component + E2E',
    badge: 'Component · E2E',
    period: '2026',
    tagline: 'A full Cypress project covering both component and end-to-end testing modes, with automated HTML and PDF reporting.',
    stack: ['JavaScript', 'React', 'Vite', 'Cypress 13', 'Mochawesome', 'PDFKit', 'Node.js 18+'],
    highlights: [
      'Component test suite (19 tests) mounting React components in isolation — Button, Counter, LoginForm and TodoList with validation, interaction and state scenarios.',
      'E2E test suite (46 tests) against a live site — form auth, checkboxes, dropdowns, dynamic loading, alerts, key presses and status codes.',
      'Automated reporting: both suites run headlessly, results merge via mochawesome, and a PDF report is generated automatically.',
      'Multi-agent workflow drafts and adversarially reviews E2E specs — a reviewer agent verifies each spec against the live DOM, catching stale-element re-clicks and flaky loading assertions.',
      'Reliable VS Code compatibility via a custom Cypress launcher that strips the ELECTRON_RUN_AS_NODE conflict before launch.',
    ],
    github: null,
  },
  'spring-backend': {
    title: 'Spring Boot E-Commerce Backend',
    badge: 'Backend',
    period: '2025',
    tagline: 'A production-ready e-commerce backend built while mastering Spring Boot, Spring Data JPA, Hibernate and Spring Security.',
    stack: ['Spring Boot', 'Spring Data JPA', 'Hibernate', 'Spring Security (JWT)', 'Stripe', 'Flyway'],
    highlights: [
      'Secure JWT authentication with role-based access control.',
      'Shopping cart management, checkout and order APIs, with Stripe payment integration.',
      'Clean, scalable architecture with pagination, sorting, custom queries and efficient database interactions.',
      'Environment-based cloud deployment configuration and Flyway migrations.',
    ],
    github: 'https://github.com/Kavindu-Dilshan-Dev',
  },
  'patient-microservices': {
    title: 'Patient Management System',
    badge: 'Microservices',
    period: '2025',
    tagline: 'A scalable HealthTech backend using a microservices architecture to manage patient data.',
    stack: ['Java', 'Spring Boot', 'Spring Security (JWT)', 'gRPC', 'Apache Kafka', 'Docker', 'API Gateway', 'PostgreSQL'],
    highlights: [
      'Core services implemented: Patient, Billing, Analytics and Auth.',
      'gRPC for efficient inter-service communication and Kafka for real-time patient event streaming.',
      'APIs secured with JWT and Spring Security, integrated via an API Gateway.',
      'Services containerized with Docker and documented using Swagger / OpenAPI.',
    ],
    github: null,
  },
};
